baseURL = "http://127.0.0.1:80/"
languageCode = "en-us"
defaultContentLanguage = "zh"
theme = "dream"
title = "Soarch Zone"
enableRobotsTXT = true
hasCJKLanguage = true

[params]
### theme common
author = "Summer Cocoa"
description = "Soarch Zone"
favicon = "img/favicon.ico"
avatar = "https://oss.soarch.top/11622109954_.pic_hd.jpg"

### dream theme
headerTitle = "SummerCocoa的生活"
motto = "颓废者 is moving～～～"
email = "1098517478@qq.com"

showSummaryCoverInPost = false
hasTwitterEmbed = false
fixedNav = true
# siteStartYear =
shareInAside = false
reversePostAndAside = true
enableSearch = false
rss = false

# dark mode
backgroundDark = "black"
darkNav = true
dark404 = true

[params.advanced]
customCSS = ["css/detail.css"]
customJS = []
