baseURL = "https://blog.soarch.top"
languageCode = "zh-Hans"
defaultContentLanguage = "zh"
enableRobotsTXT = true
hasCJKLanguage = true

theme = "dream"
title = "Soarch空间"
# copyright = "Copyright@2021"


[params]
### theme common
author = "Summer Cocoa"
description = "Soarch空间"
favicon = "/img/favicon.ico"
avatar = "https://oss.soarch.top/avatar.jpg"

### dream theme
headerTitle = "二宝 & 阿右's Life"
motto = "This man is moving slowly slowly slowly～～～"
# github = "CocoaSummer"

## config
enableSearch = true
fixedNav = true
hasTwitterEmbed = false
reversePostAndAside = false
rss = false
shareInAside = false
showSummaryCoverInPost = false
siteStartYear = 2016

## style
# defaultDark = true
background = "#fff"
backgroundImage = "https://oss.soarch.top/background.jpg"
linkColor = "black"
backgroundDark = "#333"
backgroundImageDark = "https://oss.soarch.top/background-dark.jpg"
darkLinkColor = "white"
darkNav = true
dark404 = true

[params.advanced]
customCSS = ["css/custom.css"]
customJS = []

[params.experimental]
jsDate = true
jsDateFormat = "yyyy/MM/dd"


### 搜索
[outputs]
home = ["HTML", "RSS", "JSON"]


### md中内嵌html，必须设置
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
