baseURL = "http://localhost:7000/"
languageCode = "en-us"
defaultContentLanguage = "zh"
theme = "dream"
title = "Soarch"
enableRobotsTXT = true
hasCJKLanguage = false

[params]
  showSummaryCoverInPost = false
  hasTwitterEmbed = false
  fixedNav = true
  siteStartYear = 2020
  shareInAside = false
  reversePostAndAside = true
  enableSearch = false

  author = "Summer Cocoa"
  headerTitle = "SummerCocoa的小窝"
  description = "g1eny0ung 的生活记录～"
  motto = "与其感慨路难行，不如马上出发。"
  avatar = "/img/qrcode.jpg"
  email = "1098517478@qq.com"
  rss = false

  # dark mode
  backgroundDark = "black"
  darkNav = true
  dark404 = true

  [params.advanced]
    customCSS = ["css/detail.css"]
    customJS = []
